server {
    # Listen on port 443 with SSL (HTTPS)
    listen 443 ssl;
    listen [::]:443 ssl;

    # The domain name this server responds to
    server_name mabuyahy.42.fr;

    # SSL certificate files (generated in Dockerfile)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    # Where the WordPress files are
    root /var/www/html/wordpress;
    index index.php index.html;

    # Handle all requests
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Forward .php requests to PHP-FPM (WordPress container)
    location ~ \.php$ {
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}